spring.datasource.url=jdbc:postgresql://localhost:5432/kakeibo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#Hibernate/JPA×勝手にテーブルを作らせない
spring.jpa.hibernate.ddl-auto=none