#動作確認用に固定ユーザーを設定
spring.security.user.name=user
spring.security.user.password=password

# MyBatisのMapper XML配置場所
mybatis.mapper-locations=classpath*:mapper/**/*.xml
# DBのsnake_caseをJavaのcamelCaseへ自動変換
mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.url=jdbc:postgresql://localhost:5432/kakeibo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#Hibernate/JPA×勝手にテーブルを作らせない
spring.jpa.hibernate.ddl-auto=none